name: "get BTC to Telegram"
daily: 
  - 01:00"
  - 13:00
work:
  - fetch:
      name: "Lấy giá BTC"
      url: "https://api.binance.com/api/v3/ticker/price?symbol=BTCUSDT"
      method: "GET"
      as: btc
      timeout: 1000
      success:
        - fetch:
            name: "Gửi đến Telegram"
            url: "https://api.telegram.org/bot{{ secret.telegram.key }}/sendMessage"
            method: "POST"
            as: "telegram"
            headers:
              content-type: "application/json"
            body:
              chat_id: "-5077473015"
              text: "Kitwork BOT:\n - BTC/USDT: {{ btc.price | dollar  }}"
            success:
            error:

      error:

success:
  - log: "Gửi thành công BTC/USDT đến Telegram"
error:
  - log: "Đã có lỗi xảy ra"
