cron:  # or empty
   name: "example api"
   schedules:
   - "0 2 * * *"
   - "0 3 * * *"

   actions:
 
   - fetch:
         name: "Lấy ip"
         url: "https://api.ipify.org?format=json"
         method: "GET"
         timeout: 200
         success: 
         error: 
       

   success: 
     - log: "Kết quả {{ .Result }}"
   error: 
      - log: "lỗi"